# 1.  The guests who are from USA

SELECT GUEST_LNAME, GUEST_FNAME, GUEST_COUNTRY
FROM HOTEL_MANAGEMENT.GUEST
WHERE GUEST_COUNTRY = 'USA';

# 2. Find the room details for a particular guests

SELECT R.ROOM_NUM, R.ROOM_FLOOR, G.GUEST_LNAME, G.GUEST_FNAME, G.GUEST_CITY
FROM HOTEL_MANAGEMENT.ROOM R
INNER JOIN HOTEL_MANAGEMENT.GUEST G ON R.ROOM_ID = G.ROOM_ID;


# 3. Calculate the number of staff that work at a particular restaurant

SELECT S.STAFF_LNAME, S.STAFF_FNAME, R.REST_NAME,
	(SELECT COUNT(*) 
		FROM HOTEL_MANAGEMENT.STAFF S2 WHERE S2.REST_ID = R.REST_ID) AS NUM_STAFF
		FROM HOTEL_MANAGEMENT.STAFF S
		JOIN HOTEL_MANAGEMENT.RESTAURANT R ON S.REST_ID = R.REST_ID
		WHERE S.STAFF_POSITION = 'CHEF';







